# Generated by Django 3.1.2 on 2020-11-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_url_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='User',
            new_name='user',
        ),
    ]
